### PR TITLE
#163388207 Setup react router v4 with (react-router-dom)

### PR DESCRIPTION
**Pull request by TooColline**
**What does this PR do**
It enables routing for our application with react-router-v4

**Description of task to be completed**
- Create components and views folders
- Add home, login and navigation components
- Add home, login and navigation views
- Route the home and login pages

**How should this be manually tested**
1. Clone this repository with ```git clone https://github.com/andela/ah-bird-box-frontend.git```
2. Cd into the project with ```cd ah-bird-box-frontend```
3. Checkout to the specific branch with ```git checkout ch-react-router-v4-163388207```
4. Run ```npm install``` to install all the dependencies of the application
5. Run ```npm start```

**Any background context you want to provide?**
The login route displays a dummy login form.

**What are the relevant pivotal tracker stories?**
[#163388207](https://www.pivotaltracker.com/n/projects/2240063)

**Screenshots (if appropriate)**

**The home route or "/" page**
image

**The login route or "/login" page**
image

### CODE REVIEW

**Review by calebrotich — APPROVED** [review]
LGTM

**Comment by unah254** [comment]
Works as expected. Good work

**Review by unah254 — APPROVED** [review]
Works as expected. Good work!

**Review by bryan-munene — APPROVED** [review]
LGTM

**Pull request merged**
